version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db-php
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456 
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - '333:80'
      environment:
          PMA_HOST: db
      depends_on:
          - db